sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating image with dockerfile"
  - docker build -t kahlominkyung/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true kahlominkyung/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: docker-react-app
  env: Dockerreactapp-env
  bucket-name: elasticbeanstalk-us-west-2-202951487430
  bucket-path: elasticbeanstalk-us-west-2-202951487430
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
